# config.yaml
paths:
  data_dir: "data"
  cached_data_dir: "cached/data"
  cached_model_dir: "cached/model"
  cached_plots_dir: "results/plots"
  raw_data_file: "data/mbti_1.csv"

models:
  xgboost_multiclass:
    name: "xgboost_multiclass"
    file_prefix: "xgb_multi"
    params:
      n_estimators: 379
      max_depth: 7
      learning_rate: 0.06426980635
      colsample_bytree: 0.8166031869068445
      subsample: 0.8070259980080767
      random_state: 42

embeddings:
  method: "tfidf"
  max_features: 5000
  min_df: 0.01
  max_df: 0.95
  ngram_range: [1, 3]
  use_idf: true
  sublinear_tf: true

data_processing:
  test_size: 0.2
  random_state: 42
  validation_size: 0.1
  text_column: "posts"
  target_column: "type"
  clean_text: true
  remove_urls: true
  remove_mentions: false
  lowercase: true
  tuning_n_iter: 30
  tuning_cv_folds: 3

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/training.log"

features:
  use_tfidf: true
  use_word_count: true
  use_char_count: true
  use_sentence_count: true
  use_avg_word_length: true
